schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "VPCEnvironmentInput"
  types:
    VPCEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        vpc_cidr_block:
          type: string
          description: "The CIDR range for your VPC"
          default: 192.168.0.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        vpc_instance_tenancy:
            type: string
            description: "VPC tenancy"
            default: default
        vpc_name:
            type: string
            description: "test vpc"
            default: SampleVPC
        private_cidrs:
            type: string
            description: "Private subnet cidr"
            default: 192.168.1.0/26
            pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|26))
        private_subnet_name:
            type: string
            description: "Name of Subnet"
            default: SampleSubnet